export const GET_PEOPLE = 'GET_PEOPLE'
export const CLEAR_DATA = 'CLEAR_DATA'
export const LOAD_PEOPLE_REQUEST = 'LOAD_PEOPLE_REQUEST'
export const LOAD_PEOPLE_SUCCESS = 'LOAD_PEOPLE_SUCCESS'

export const VIEW_PERSON = 'VIEW_PERSON'
export const DELETE_PERSON = 'DELETE_PERSON' 
